api:
  dashboard: true
  debug: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "tcp://docker-proxy:2375"
    watch: true
    exposedbydefault: false

accessLog:
  filePath: "/data/access.log"

certificatesResolvers:
  http:
    acme:
      email: admin@ricsanfre.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
